trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: '0.1.0'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: Assembly-Info-NetCore@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*.csproj'
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    GeneratePackageOnBuild: true
    PackageId: 'SharpSource'
    Authors: 'Jeroen Vannevel'
    Description: 'Protect your code from runtime issues through static analysis.'
    PackageProjectUrl: 'https://github.com/vannevelj/SharpSource'
    RepositoryUrl: 'https://github.com/vannevelj/SharpSource'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

- task: VsixToolsUpdateVersion@2
  inputs:
    FileName: '$(Build.SourcesDirectory)\sharpsource\sharpsource.Vsix\source.extension.vsixmanifest'
    VersionNumber: '$(Build.BuildNumber)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\SharpSource.Tests.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: CopyFiles@2
  inputs:
    Contents: '**\?(*.vsix|publishManifest.json|README.md|*.nupkg)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'