trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: '0.1.0'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: Assembly-Info-NetCore@2
  inputs:
    PackageId: 'SharpSource'
    Authors: 'Jeroen Vannevel'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'

- task: VsixToolsUpdateVersion@2
  inputs:
    FileName: '$(Build.SourcesDirectory)\sharpsource\sharpsource.Vsix\source.extension.vsixmanifest'
    VersionNumber: '$(Build.BuildNumber)'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\sharpsource.Test.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: CopyFiles@2
  inputs:
    Contents: '**\?(*.vsix|publishManifest.json|README.md|*.nupkg)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'