pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: '0.3.0'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: Assembly-Info-NetCore@2
  inputs:
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'

- task: VsixToolsUpdateVersion@2
  inputs:
    FileName: '$(Build.SourcesDirectory)\sharpsource\sharpsource.Vsix\source.extension.vsixmanifest'
    VersionNumber: '$(Build.BuildNumber)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\SharpSource.Tests.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/bin/**/*.nuspec'
    versioningScheme: 'byBuildNumber'

- task: CopyFiles@2
  inputs:
    Contents: '**\?(*.vsix|publishManifest.json|README.md|*.nupkg)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'