name: test

on: push

concurrency:
  group: ${{ github.head_ref }}-test
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run tests
        run: dotnet test