name: Build and Test

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.head_ref }}-test
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet Packages
        run: nuget restore sharpsource.sln

      - name: Build app for release
        run: msbuild sharpsource.sln -t:rebuild -property:Configuration=Release
        env: 
          DeployExtension: False

      - name: Run tests
        run: dotnet test --verbosity normal

      - name: Collect artifacts - VSIX
        uses: actions/upload-artifact@v2
        with:
          name: MappingGenerator-VSIX
          path: SharpSource\SharpSource.Vsix\bin\Release\SharpSource.vsix

      - name: Collect artifacts - nugets
        uses: actions/upload-artifact@v2
        with:
          name: SharpSource-Nugets
          path: '**/SharpSource*.nupkg'