name: build

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.head_ref }}-build
  cancel-in-progress: true

jobs:
  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGet Packages
        run: nuget restore sharpsource.sln

      - name: Check format
        run: dotnet format --no-restore --verify-no-changes