name: Format

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.head_ref }}-build
  cancel-in-progress: true

jobs:
  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet Packages
        run: nuget restore sharpsource.sln

      - name: Build app for release
        run: msbuild sharpsource.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Check format
        run: dotnet format --no-restore --verify-no-changes